package com.getaltair.kairos.dashboard.server

import com.getaltair.kairos.dashboard.auth.AuthSessionManager
import com.getaltair.kairos.dashboard.auth.DashboardAuthState
import com.getaltair.kairos.dashboard.state.DashboardStateHolder
import com.getaltair.kairos.dashboard.state.DisplayMode
import io.ktor.http.HttpStatusCode
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.install
import io.ktor.server.engine.EmbeddedServer
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty
import io.ktor.server.plugins.ContentTransformationException
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation
import io.ktor.server.plugins.statuspages.StatusPages
import io.ktor.server.request.receive
import io.ktor.server.request.uri
import io.ktor.server.response.respond
import io.ktor.server.routing.get
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import kotlinx.serialization.Serializable
import org.slf4j.LoggerFactory

@Serializable
data class HealthResponse(val status: String)

@Serializable
data class StatusResponse(
    val totalHabits: Int,
    val completedHabits: Int,
    val connectionStatus: String,
    val isStale: Boolean,
    val displayMode: String,
)

@Serializable
data class ModeRequest(val mode: String)

@Serializable
data class ModeResponse(val status: String, val mode: String)

@Serializable
data class ErrorResponse(val status: String = "error", val error: String)

/**
 * Request body for `POST /auth/confirm`.
 *
 * @property sessionToken the one-time token embedded in the QR code, generated by [AuthSessionManager.createPendingSession]
 * @property firebaseIdToken the Firebase ID token obtained by the mobile app after Firebase sign-in
 */
@Serializable
data class AuthConfirmRequest(val sessionToken: String, val firebaseIdToken: String)

/**
 * Response body for `POST /auth/confirm`.
 *
 * On success, [success] is `true` and [message] contains the authenticated user ID.
 * On failure, [success] is `false` and [message] describes the error.
 *
 * @property success whether the authentication confirmation succeeded
 * @property message the user ID on success, or an error description on failure
 */
@Serializable
data class AuthConfirmResponse(val success: Boolean, val message: String)

/**
 * Response body for `GET /auth/status`.
 *
 * @property authenticated whether the dashboard currently has a confirmed session
 * @property userId the Firebase UID of the authenticated user, or `null` when unauthenticated
 */
@Serializable
data class AuthStatusResponse(val authenticated: Boolean, val userId: String? = null)

class StatusServer(
    private val port: Int,
    private val host: String = "0.0.0.0",
    stateHolder: DashboardStateHolder? = null,
    private val authSessionManager: AuthSessionManager? = null,
) {
    private val logger = LoggerFactory.getLogger(StatusServer::class.java)
    private var server: EmbeddedServer<*, *>? = null

    /** Mutable so Main can update the reference after QR authentication. */
    @Volatile
    var stateHolder: DashboardStateHolder? = stateHolder

    fun start() {
        server = embeddedServer(Netty, port = port, host = host) {
            install(ContentNegotiation) {
                json()
            }
            install(StatusPages) {
                exception<ContentTransformationException> { call, cause ->
                    logger.warn("Bad request on {}: {}", call.request.uri, cause.message)
                    call.respond(
                        HttpStatusCode.BadRequest,
                        ErrorResponse(error = cause.message ?: "Invalid request body"),
                    )
                }
            }
            routing {
                get("/health") {
                    call.respond(HealthResponse(status = "ok"))
                }
                get("/api/status") {
                    val holder = stateHolder
                    if (holder == null) {
                        call.respond(
                            HttpStatusCode.ServiceUnavailable,
                            ErrorResponse(error = "Dashboard not yet authenticated"),
                        )
                        return@get
                    }
                    val state = holder.state.value
                    call.respond(
                        StatusResponse(
                            totalHabits = state.totalHabits,
                            completedHabits = state.completedCount,
                            connectionStatus = state.connectionStatus.name,
                            isStale = state.isStale,
                            displayMode = state.displayMode.name.lowercase(),
                        ),
                    )
                }
                post("/mode") {
                    val holder = stateHolder
                    if (holder == null) {
                        call.respond(
                            HttpStatusCode.ServiceUnavailable,
                            ErrorResponse(error = "Dashboard not yet authenticated"),
                        )
                        return@post
                    }
                    val request = try {
                        call.receive<ModeRequest>()
                    } catch (e: Exception) {
                        logger.warn("Malformed /mode request: {}", e.message)
                        call.respond(
                            HttpStatusCode.BadRequest,
                            ErrorResponse(
                                error = "Invalid request body. Expected JSON: {\"mode\": \"active|standby\"}",
                            ),
                        )
                        return@post
                    }
                    logger.info(
                        "Mode change to '{}' requested from {}",
                        request.mode.lowercase(),
                        call.request.local.remoteAddress,
                    )
                    val displayMode = DisplayMode.fromString(request.mode)
                        ?: run {
                            call.respond(
                                HttpStatusCode.BadRequest,
                                ErrorResponse(error = "Invalid mode. Use 'active' or 'standby'."),
                            )
                            return@post
                        }
                    holder.setDisplayMode(displayMode)
                    call.respond(ModeResponse(status = "ok", mode = request.mode.lowercase()))
                }

                // ----- Auth endpoints --------------------------------------------------

                post("/auth/confirm") {
                    val manager = authSessionManager
                    if (manager == null) {
                        call.respond(
                            HttpStatusCode.ServiceUnavailable,
                            ErrorResponse(error = "Auth not configured"),
                        )
                        return@post
                    }
                    val request = try {
                        call.receive<AuthConfirmRequest>()
                    } catch (e: Exception) {
                        logger.warn("Malformed /auth/confirm request: {}", e.message)
                        call.respond(
                            HttpStatusCode.BadRequest,
                            ErrorResponse(error = "Invalid request body"),
                        )
                        return@post
                    }

                    val result = manager.confirmSession(
                        sessionToken = request.sessionToken,
                        firebaseIdToken = request.firebaseIdToken,
                    )

                    result.fold(
                        onSuccess = { session ->
                            call.respond(
                                HttpStatusCode.OK,
                                AuthConfirmResponse(success = true, message = session.userId),
                            )
                        },
                        onFailure = { error ->
                            when (error) {
                                is IllegalArgumentException -> call.respond(
                                    HttpStatusCode.Unauthorized,
                                    AuthConfirmResponse(false, error.message ?: "Authentication failed"),
                                )

                                is IllegalStateException -> call.respond(
                                    HttpStatusCode.Gone,
                                    AuthConfirmResponse(false, error.message ?: "Session expired"),
                                )

                                is java.io.IOException -> call.respond(
                                    HttpStatusCode.InternalServerError,
                                    AuthConfirmResponse(false, "Internal server error"),
                                )

                                else -> call.respond(
                                    HttpStatusCode.Unauthorized,
                                    AuthConfirmResponse(false, "Authentication failed"),
                                )
                            }
                        },
                    )
                }

                get("/auth/status") {
                    val manager = authSessionManager
                    if (manager == null) {
                        call.respond(AuthStatusResponse(authenticated = false))
                        return@get
                    }
                    val state = manager.authState.value
                    when (state) {
                        is DashboardAuthState.Authenticated -> call.respond(
                            AuthStatusResponse(authenticated = true, userId = state.userId),
                        )

                        else -> call.respond(
                            AuthStatusResponse(authenticated = false),
                        )
                    }
                }
            }
        }
        server?.start(wait = false)
        logger.info("StatusServer started on {}:{}", host, port)
    }

    fun stop() {
        try {
            server?.stop(1000, 2000)
        } catch (e: Exception) {
            logger.warn("Error stopping StatusServer", e)
        }
    }
}
